-- Auto-generated by tools/build_injected_forbidden.py
-- Usage:
--   local url = "https://raw.githubusercontent.com/<owner>/<repo>/<branch>/inject/entry.lua"
--   local AI = loadstring(game:HttpGet(url), url)()
--
-- If your executor does not preserve the chunk source for debug.info, set:
--   getgenv().__FORBIDDEN_BASE_URL = "https://raw.githubusercontent.com/<owner>/<repo>/<branch>/inject"
-- before loading entry.lua.

local GLOBAL_ENV = (getgenv and getgenv()) or _G

local function inferBaseUrl()
    local injectedBase = GLOBAL_ENV.__FORBIDDEN_BASE_URL
    if type(injectedBase) == "string" and injectedBase ~= "" then
        return (injectedBase:gsub("/+$", ""))
    end

    if debug and debug.info then
        local ok, source = pcall(debug.info, 1, "s")
        if ok and type(source) == "string" then
            source = source:gsub("^@", "")
            if source:match("^https?://") then
                local base = source:match("^(.*)/[^/]+$")
                if base then
                    return base
                end
            end
        end
    end

    error("Unable to infer Forbidden base URL. Use loadstring(game:HttpGet(url), url)() or set __FORBIDDEN_BASE_URL.", 0)
end

local BASE_URL = inferBaseUrl()

local NODE_CLASSES = {
    ["Forbidden"] = "ModuleScript",
    ["Forbidden/AI"] = "ModuleScript",
    ["Forbidden/AI/Assist"] = "Folder",
    ["Forbidden/AI/Assist/DetectBadPaths"] = "ModuleScript",
    ["Forbidden/AI/Assist/PathfindDistanceHelper"] = "ModuleScript",
    ["Forbidden/AI/CommonMathRequests"] = "ModuleScript",
    ["Forbidden/AI/ConfigHandler"] = "ModuleScript",
    ["Forbidden/AI/ConfigHandler/Defaults"] = "ModuleScript",
    ["Forbidden/AI/Debugging"] = "ModuleScript",
    ["Forbidden/AI/DirectMoveTo"] = "ModuleScript",
    ["Forbidden/AI/MessageQueue"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor/States"] = "Folder",
    ["Forbidden/AI/PathfindingProcessor/States/Idle"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor/States/Pathing"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor/States/Tracking"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor/TriggerCleanup"] = "ModuleScript",
    ["Forbidden/AI/PathfindingProcessor/WaypointLooper"] = "ModuleScript",
    ["Forbidden/AI/PositionalOptimization"] = "ModuleScript",
    ["Forbidden/AI/Preprogrammed - Delete Me"] = "Script",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions"] = "Folder",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - SimpleTRACK"] = "Folder",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - SimpleTRACK/README"] = "Script",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY"] = "ModuleScript",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER"] = "ModuleScript",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS"] = "ModuleScript",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT"] = "ModuleScript",
    ["Forbidden/AI/RetrackingOptimization"] = "ModuleScript",
    ["Forbidden/AI/Types"] = "ModuleScript",
    ["Forbidden/AI/Types/TConfig"] = "ModuleScript",
    ["Forbidden/AI/Types/TRequestPriority"] = "ModuleScript",
    ["Forbidden/AI/Visualization"] = "Folder",
    ["Forbidden/AI/Visualization/WaypointsVisualization"] = "ModuleScript",
    ["Forbidden/AI/antilag"] = "Script",
    ["Forbidden/AI/info"] = "Script",
    ["Forbidden/Common"] = "ModuleScript",
    ["Forbidden/Common/Storage"] = "ModuleScript",
    ["Forbidden/Common/TypeHelp"] = "ModuleScript",
    ["Forbidden/DeveloperProductHandler"] = "Folder",
    ["Forbidden/DeveloperProductHandler/ExampleUIScript"] = "Folder",
    ["Forbidden/DeveloperProductHandler/ExampleUIScript/MPSHandler"] = "LocalScript",
    ["Forbidden/DeveloperProductHandler/ServerScriptService"] = "Folder",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products"] = "Folder",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/DevProductHandler"] = "Script",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase"] = "ModuleScript",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config"] = "ModuleScript",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl"] = "Folder",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example"] = "ModuleScript",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config"] = "ModuleScript",
    ["Forbidden/Libraries"] = "Folder",
    ["Forbidden/Libraries/Tables"] = "ModuleScript",
    ["Forbidden/Math"] = "ModuleScript",
    ["Forbidden/Math/CommonMathCollection"] = "ModuleScript",
    ["Forbidden/Math/MathVisualization"] = "ModuleScript",
    ["Forbidden/Math/old"] = "ModuleScript",
    ["Forbidden/Packages"] = "Folder",
    ["Forbidden/Packages/_Index"] = "Folder",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7"] = "Folder",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes"] = "Folder",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions"] = "Folder",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor"] = "Folder",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal"] = "ModuleScript",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove"] = "ModuleScript",
    ["Forbidden/Packages/robloxstatemachine"] = "ModuleScript"
}

local MODULE_PATHS = {
    ["Forbidden"] = "modules/Forbidden/__module.lua",
    ["Forbidden/AI"] = "modules/Forbidden/AI/__module.lua",
    ["Forbidden/AI/Assist/DetectBadPaths"] = "modules/Forbidden/AI/Assist/DetectBadPaths/__module.lua",
    ["Forbidden/AI/Assist/PathfindDistanceHelper"] = "modules/Forbidden/AI/Assist/PathfindDistanceHelper/__module.lua",
    ["Forbidden/AI/CommonMathRequests"] = "modules/Forbidden/AI/CommonMathRequests/__module.lua",
    ["Forbidden/AI/ConfigHandler"] = "modules/Forbidden/AI/ConfigHandler/__module.lua",
    ["Forbidden/AI/ConfigHandler/Defaults"] = "modules/Forbidden/AI/ConfigHandler/Defaults/__module.lua",
    ["Forbidden/AI/Debugging"] = "modules/Forbidden/AI/Debugging/__module.lua",
    ["Forbidden/AI/DirectMoveTo"] = "modules/Forbidden/AI/DirectMoveTo/__module.lua",
    ["Forbidden/AI/MessageQueue"] = "modules/Forbidden/AI/MessageQueue/__module.lua",
    ["Forbidden/AI/PathfindingProcessor"] = "modules/Forbidden/AI/PathfindingProcessor/__module.lua",
    ["Forbidden/AI/PathfindingProcessor/States/Idle"] = "modules/Forbidden/AI/PathfindingProcessor/States/Idle/__module.lua",
    ["Forbidden/AI/PathfindingProcessor/States/Pathing"] = "modules/Forbidden/AI/PathfindingProcessor/States/Pathing/__module.lua",
    ["Forbidden/AI/PathfindingProcessor/States/Tracking"] = "modules/Forbidden/AI/PathfindingProcessor/States/Tracking/__module.lua",
    ["Forbidden/AI/PathfindingProcessor/TriggerCleanup"] = "modules/Forbidden/AI/PathfindingProcessor/TriggerCleanup/__module.lua",
    ["Forbidden/AI/PathfindingProcessor/WaypointLooper"] = "modules/Forbidden/AI/PathfindingProcessor/WaypointLooper/__module.lua",
    ["Forbidden/AI/PositionalOptimization"] = "modules/Forbidden/AI/PositionalOptimization/__module.lua",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY"] = "modules/Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ALLY/__module.lua",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER"] = "modules/Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The MONSTER/__module.lua",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS"] = "modules/Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV - The ZOMBS/__module.lua",
    ["Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT"] = "modules/Forbidden/AI/Preprogrammed - Delete Me/@CritDEV Solutions/@CritDEV- The UNIT/__module.lua",
    ["Forbidden/AI/RetrackingOptimization"] = "modules/Forbidden/AI/RetrackingOptimization/__module.lua",
    ["Forbidden/AI/Types"] = "modules/Forbidden/AI/Types/__module.lua",
    ["Forbidden/AI/Types/TConfig"] = "modules/Forbidden/AI/Types/TConfig/__module.lua",
    ["Forbidden/AI/Types/TRequestPriority"] = "modules/Forbidden/AI/Types/TRequestPriority/__module.lua",
    ["Forbidden/AI/Visualization/WaypointsVisualization"] = "modules/Forbidden/AI/Visualization/WaypointsVisualization/__module.lua",
    ["Forbidden/Common"] = "modules/Forbidden/Common/__module.lua",
    ["Forbidden/Common/Storage"] = "modules/Forbidden/Common/Storage/__module.lua",
    ["Forbidden/Common/TypeHelp"] = "modules/Forbidden/Common/TypeHelp/__module.lua",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase"] = "modules/Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/__module.lua",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config"] = "modules/Forbidden/DeveloperProductHandler/ServerScriptService/Products/ProductBase/Config/__module.lua",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example"] = "modules/Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/__module.lua",
    ["Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config"] = "modules/Forbidden/DeveloperProductHandler/ServerScriptService/Products/impl/Example/Config/__module.lua",
    ["Forbidden/Libraries/Tables"] = "modules/Forbidden/Libraries/Tables/__module.lua",
    ["Forbidden/Math"] = "modules/Forbidden/Math/__module.lua",
    ["Forbidden/Math/CommonMathCollection"] = "modules/Forbidden/Math/CommonMathCollection/__module.lua",
    ["Forbidden/Math/MathVisualization"] = "modules/Forbidden/Math/MathVisualization/__module.lua",
    ["Forbidden/Math/old"] = "modules/Forbidden/Math/old/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/State/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Classes/Transition/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/deepCopy/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Functions/mergeTables/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Signal/__module.lua",
    ["Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove"] = "modules/Forbidden/Packages/_Index/prooheckcp_robloxstatemachine@1.1.7/robloxstatemachine/Vendor/Trove/__module.lua",
    ["Forbidden/Packages/robloxstatemachine"] = "modules/Forbidden/Packages/robloxstatemachine/__module.lua"
}

local NODE_METHODS = {}
local NODE_MT = {
    __index = function(self, key)
        local method = NODE_METHODS[key]
        if method ~= nil then
            return method
        end

        return self._children[key]
    end,
}

local nodes = {}

local function splitId(id)
    local parts = {}
    for part in string.gmatch(id, "[^/]+") do
        table.insert(parts, part)
    end
    return parts
end

local function ensureNode(id)
    local existing = nodes[id]
    if existing then
        return existing
    end

    local parts = splitId(id)
    local name = parts[#parts]
    local parentId = id:match("^(.*)/[^/]+$")
    local parentNode = nil
    if parentId then
        parentNode = ensureNode(parentId)
    end

    local node = setmetatable({
        _forbiddenNode = true,
        _id = id,
        _children = {},
        Name = name,
        ClassName = NODE_CLASSES[id] or "Folder",
        Parent = parentNode,
    }, NODE_MT)

    nodes[id] = node

    if parentNode then
        parentNode._children[name] = node
    end

    return node
end

for id, _ in pairs(NODE_CLASSES) do
    ensureNode(id)
end

function NODE_METHODS:GetChildren()
    local children = {}
    for _, child in pairs(self._children) do
        table.insert(children, child)
    end

    table.sort(children, function(a, b)
        return a.Name < b.Name
    end)

    return children
end

function NODE_METHODS:GetDescendants()
    local descendants = {}

    local function walk(node)
        for _, child in ipairs(node:GetChildren()) do
            table.insert(descendants, child)
            walk(child)
        end
    end

    walk(self)
    return descendants
end

function NODE_METHODS:FindFirstChild(name, recursive)
    local direct = self._children[name]
    if direct then
        return direct
    end

    if recursive then
        for _, child in ipairs(self:GetChildren()) do
            local found = child:FindFirstChild(name, true)
            if found then
                return found
            end
        end
    end

    return nil
end

function NODE_METHODS:WaitForChild(name, timeout)
    local found = self:FindFirstChild(name, false)
    if found then
        return found
    end

    error(("Synthetic node %s has no child named %s"):format(self:GetFullName(), tostring(name)), 2)
end

function NODE_METHODS:IsA(className)
    return self.ClassName == className
end

function NODE_METHODS:GetFullName()
    local parts = {}
    local current = self
    while current do
        table.insert(parts, 1, current.Name)
        current = current.Parent
    end
    return table.concat(parts, ".")
end

function NODE_METHODS:Destroy()
    if self.Parent then
        self.Parent._children[self.Name] = nil
    end
    nodes[self._id] = nil
end

local runtime = {}
local moduleCache = {}
local loading = {}

function runtime:getNode(id)
    local node = nodes[id]
    if not node then
        error("Unknown Forbidden synthetic node: " .. tostring(id), 2)
    end
    return node
end

local function encodeUrlPath(path)
    return (path:gsub("([^%%w%%-%%._~/@])", function(char)
        return string.format("%%%02X", string.byte(char))
    end))
end

    local function syntheticRequire(target)
        if typeof(target) == "Instance" then
            return require(target)
        end

    if type(target) ~= "table" or not target._forbiddenNode then
        error("Forbidden synthetic require expected a synthetic node or Instance.", 2)
    end

    if target.ClassName ~= "ModuleScript" then
        error("Attempted to require non-ModuleScript synthetic node: " .. target:GetFullName(), 2)
    end

    local moduleId = target._id
    if moduleCache[moduleId] ~= nil then
        return moduleCache[moduleId]
    end

    if loading[moduleId] then
        error("Circular synthetic require detected for " .. moduleId, 2)
    end

    local relPath = MODULE_PATHS[moduleId]
    if not relPath then
        error("No remote module path registered for " .. moduleId, 2)
    end

    loading[moduleId] = true

    local url = BASE_URL .. "/" .. encodeUrlPath(relPath)
    local source = game:HttpGet(url)
    local prelude = "local script, require, runtime = ...\nlocal __FORBIDDEN_ROOT = runtime:getNode('Forbidden')\n"
    local chunk, loadErr = loadstring(prelude .. source, url)
    if not chunk then
        loading[moduleId] = nil
        error(loadErr, 0)
    end

    local ok, result = pcall(chunk, target, syntheticRequire, runtime)
    loading[moduleId] = nil
    if not ok then
        error(result, 0)
    end

    if result == nil then
        result = true
    end

    moduleCache[moduleId] = result
    return result
    end

    runtime.require = syntheticRequire
    runtime.remoteRequire = function(target)
        if type(target) == "string" then
            target = runtime:getNode(target)
        end
        return syntheticRequire(target)
    end
    GLOBAL_ENV.__FORBIDDEN_LAST_RUNTIME = runtime

    return syntheticRequire(runtime:getNode("Forbidden/AI"))
